# callable workflows' jobs appear in the calling workflow's run, so clicking this workflow in GitHub shows no runs
name: Callable CMake Build

on:
  workflow_dispatch:
  workflow_call:

# no concurrency constraints for callable workflows, set in caller instead

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: build ${{ matrix.preset }}
    env:
      "VCPKG_BINARY_SOURCES": "clear;files,${{ github.workspace }}/vcpkg_cache,readwrite"

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            name: Windows x86_64
            preset: windows-x64-mingw

    steps:
      - name: Debug action
        uses: hmarr/debug-action@v3

      - name: checkout workspace
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run CMake Composite Action
        uses: ./.github/actions/build
        with:
          preset: ${{ matrix.preset }}
          target: bundle

      - name: list bundle artifacts
        run: ls -R
        working-directory: ./build/bundle/

      - name: list program artifacts
        run: ls -R
        working-directory: ./build/programs/ziti-edge-tunnel/

      - name: upload bundle artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.preset }}
          path: ./build/bundle/ziti-edge-tunnel-*.zip 
          if-no-files-found: error
